// See https://aka.ms/new-console-template for more information

//Program.cs
using System; 

namespace Appdevhb25.SheilaMayJaro
{
    internal class Program
    {
        static void Main(string[] args)
        {
            // Aufgabe01.PrintA.Start();
            // Aufgabe02.TimeTable.Start();
            // Aufgabe03.SumOverRange.Start();
            // Aufgabe04.Divisibility.Start();
            // Aufgabe05.PrintLine.Start();
            // Aufgabe06.PrintRectangle.Start();
            // Aufgabe07.PrintTriangle.Start();
            // Aufgabe08.PrintTriangle2.Start();
            // Aufgabe09.PrintEmptySquares.Start();
            // Aufgabe10.PrintTriangle3.Start();
            // Aufgabe10.PrintTriangle3.PrintTriangle(5);
            // Console.WriteLine();
            // Aufgabe11.CheckPrime.Start();
            // Console.WriteLine(Aufgabe11.CheckPrime.PrimeNumber(25));
            // Console.WriteLine(Aufgabe11.CheckPrime.PrimeNumber(456));
            // Console.WriteLine(Aufgabe11.CheckPrime.PrimeNumber(13));
            // Aufgabe12.Fibonacci.Start();
            // Aufgabe13.PrintDeltoid.Start();
            // Aufgabe13.PrintDeltoid.PrintRhombus(13);
            // Console.WriteLine(); 
            // Aufgabe13.PrintDeltoid.PrintRhombus(7);
            // Console.WriteLine(); 
            // Aufgabe13.PrintDeltoid.PrintRhombus(5); 
            // Aufgabe14.Circle.Start(); 
            // System.Console.WriteLine();
            // Aufgabe15.ChristmasTree.Start();
            // Console.WriteLine(); 
            // Aufgabe16.HigherOrLower.Start();
            // Console.WriteLine(); 
            // Aufgabe17.CalculationOfPiLeibnizSeries.Start();
            // Console.WriteLine(); 
            // Aufgabe19.PrimitiveDatatypes.Start();
            // Console.WriteLine();
            // Aufgabe20.Factorial.Start();
            // Console.WriteLine();
            // Aufgabe21.FactorialExtended.Start(); 
            // System.Console.WriteLine();
            // Aufgabe22.DivideAndRule.Start();
            // Console.WriteLine();
            //Aufgabe23.CountInSmallSteps.Start(); 
            // Console.WriteLine(); 
            //Aufgabe24.RoundNumbers.Start(); 
            //Console.WriteLine(); 
            // Aufgabe25.ValidateInput.Start();
            // Console.WriteLine(); 
            // Aufgabe26.DriversLicense.Start();
            // Console.WriteLine(); 
            // Aufgabe27.Generations.Start();
            // Console.WriteLine(); 
            // Aufgabe28.Participants.Start(); 
            // Console.WriteLine(); 
            // Aufgabe29.ParticipantsTwo.Start();
            // Console.WriteLine(); 
            // Aufgabe30.ParticipantsThree.Start();
            // Console.WriteLine(); 
            // Aufgabe31.RandomNumberArray.Start();
            // Console.WriteLine(); 
            // Aufgabe32.SumOfDigits.Start(); 
            // System.Console.WriteLine();
            // Aufgabe33.CopyArray.Start();
            // Console.WriteLine();
            // Aufgabe34.CopyReverse.Start();
            // Console.WriteLine(); 
            // Aufgabe35.BubbleSort.Start(); 
            // Console.WriteLine();
            // Aufgabe37.TwoDimensionalArray.Start();
            // Console.WriteLine(); 
            // Aufgabe38.PascalTriangle.Start();
            // Console.WriteLine(); 
            // Aufgabe39.TicTacToe.Start();
            // Console.WriteLine(); 
            // Aufgabe41.CinemaRevenueExercise.Start();
            // Console.WriteLine(); 
            //Aufgabe41.JaggedArrayRepetition.Start(); 
            // Console.WriteLine(); 
            // Aufgabe42.ReverseString.Start();
            // Console.WriteLine(); 
            // Aufgabe43.ArraySearch.Start(); 
            // System.Console.WriteLine();
            // Aufgabe44.HighlightHesse.Start(); 
            // System.Console.WriteLine();
            // Aufgabe45.CountLettersAndSymbols.Start(); 
            // System.Console.WriteLine();
            // Aufgabe46.ReplaceString.Start();
            // System.Console.WriteLine();
            // Aufgabe47Bonus.ReplaceStringRegex.Start(); 
            // System.Console.WriteLine();
            // Aufgabe48.ValidatePhoneNumber.Start();
            // System.Console.WriteLine();
            // CalendarIntroTODO.CalendarIntro.Start(); 
            // System.Console.WriteLine();
            // Aufgabe50.WhenAndWhere.Start(); 
            // System.Console.WriteLine();
            // Aufgabe51.MyBirthday.Start(); 
            // System.Console.WriteLine();
            // Aufgabe52.ClaculateSundays.Start(); 
            // System.Console.WriteLine();
            // Aufgabe53.CalculateWorkingDays.Start(); 
            // System.Console.WriteLine();
            // Aufgabe55.ParticipantsList.Start();
            // System.Console.WriteLine();
            // Aufgabe56.ParticipantsList2.Start(); 
            // System.Console.WriteLine();
            // Aufgabe57.Square.Start(); 
            // System.Console.WriteLine();
            // Aufgabe58VertiefteAufgabe.PrintFileFormatted.Start(); 
            // System.Console.WriteLine();
            // Aufgabe59.Inventory.Start(); 
            // System.Console.WriteLine();
            // Aufgabe60Bonus.Directories.Start(); 
            // System.Console.WriteLine();
            // Aufgabe61Bonus.MoreDirectories.Start(); 
            // System.Console.WriteLine();
            // Aufgabe62.ReadAndDisplayCSV.Start(); 
            // System.Console.WriteLine();
            // Aufgabe63.ProcessNumbers.Start(); 
            // System.Console.WriteLine();
            // Aufgabe64And65.Cars.Start();
            // System.Console.WriteLine();
            // Aufgabe66.PersonalInformations.Start();
            // System.Console.WriteLine();
            // Aufgabe67.Inventory2.Start(); 
            // System.Console.WriteLine();
            // Aufgabe68.Aufgabe68.Start(); 
            // System.Console.WriteLine();
            // Aufgabe69.Aufgabe69.Start(); 
            // System.Console.WriteLine();
            // Aufgabe70.Inheritance.Start(); 
            // System.Console.WriteLine();
            // Aufgabe71.Inheritance.Start(); 
            // System.Console.WriteLine();
            // Aufgabe72Bonus.Aufgabe72Bonus.Start();
            // System.Console.WriteLine();
            // Aufgabe73.Aufgabe73.Start(); 
            // System.Console.WriteLine();
            // Aufgabe74.List.Start();
            // System.Console.WriteLine();
            // Aufgabe75VertiefteAufgabe.Aufgabe75.Start();
            // System.Console.WriteLine();
            // Aufgabe76Bonus.Aufgabe76.Start(); 
            // System.Console.WriteLine();
            // Aufgabe77.Aufgabe77.Start(); 
            // System.Console.WriteLine();
            // Aufgabe78.Aufgabe78.Start();  
            // System.Console.WriteLine();
            // Aufgabe79.StreamingPlatform.Start();
            // System.Console.WriteLine();
            // Aufgabe81.TicketSystem.Start(); 
            // System.Console.WriteLine();
            // Aufgabe82.Aufgabe82.Start(); 
            // System.Console.WriteLine();
            // Aufgabe83.Aufgabe83.Start(); 
            // System.Console.WriteLine();
            // Aufgabe84.Aufgabe84.Start(); 
            // System.Console.WriteLine();
            // Aufgabe85.Aufgabe85.Start(); 
            // System.Console.WriteLine();
            // Aufgabe86.Aufgabe86.Start();
            // System.Console.WriteLine();
            Aufgabe87.Aufgabe87.Start(); 
            System.Console.WriteLine();
            // Aufgabe91.Aufgabe91.Start(); 
            // System.Console.WriteLine();
            Aufgabe89.Aufgabe89.Start(); 
            System.Console.WriteLine();
        }
    }
}