Select country.name, geo_sea.sea
From country
Left Outer Join geo_sea on geo_sea.country = country.code  

# name, sea
'Afghanistan', NULL
'Albania', 'Mediterranean Sea'
'Algeria', 'Mediterranean Sea'
'American Samoa', 'Pacific Ocean'
'Andorra', NULL
'Angola', 'Atlantic Ocean'
'Angola', 'Atlantic Ocean'
'Angola', 'Atlantic Ocean'
'Angola', 'Atlantic Ocean'
'Angola', 'Atlantic Ocean'
'Angola', 'Atlantic Ocean'
'Angola', 'Atlantic Ocean'
'Anguilla', 'Caribbean Sea'
'Anguilla', 'Atlantic Ocean'
'Antigua and Barbuda', 'Caribbean Sea'
'Antigua and Barbuda', 'Atlantic Ocean'
'Argentina', 'Atlantic Ocean'
'Argentina', 'Atlantic Ocean'
'Argentina', 'Atlantic Ocean'
'Argentina', 'Atlantic Ocean'
'Argentina', 'Atlantic Ocean'
'Armenia', NULL
'Aruba', 'Caribbean Sea'
'Australia', 'Indian Ocean'
'Australia', 'Pacific Ocean'
'Australia', 'Indian Ocean'
'Australia', 'Pacific Ocean'
'Australia', 'Indian Ocean'
'Australia', 'Indian Ocean'
'Australia', 'Pacific Ocean'
'Australia', 'Indian Ocean'
'Australia', 'Pacific Ocean'
'Australia', 'Indian Ocean'
'Austria', NULL
'Azerbaijan', NULL
'Bahamas', 'Atlantic Ocean'
'Bahrain', 'Persian Gulf'
'Bangladesh', 'Gulf of Bengal'
'Barbados', 'Atlantic Ocean'
'Belarus', NULL
'Belgium', 'North Sea'
'Belize', 'Caribbean Sea'
'Benin', 'Atlantic Ocean'
'Bermuda', 'Atlantic Ocean'
'Bhutan', NULL
'Bolivia', NULL
'Bosnia and Herzegovina', 'Mediterranean Sea'
'Botswana', NULL
'Brazil', 'Atlantic Ocean'
'Brazil', 'Atlantic Ocean'
'Brazil', 'Atlantic Ocean'
'Brazil', 'Atlantic Ocean'
'Brazil', 'Atlantic Ocean'
'Brazil', 'Atlantic Ocean'
'Brazil', 'Atlantic Ocean'
'Brazil', 'Atlantic Ocean'
'Brazil', 'Atlantic Ocean'
'Brazil', 'Atlantic Ocean'
'Brazil', 'Atlantic Ocean'
'Brazil', 'Atlantic Ocean'
'Brazil', 'Atlantic Ocean'
'Brazil', 'Atlantic Ocean'
'Brazil', 'Atlantic Ocean'
'Brazil', 'Atlantic Ocean'
'British Virgin Islands', 'Caribbean Sea'
'British Virgin Islands', 'Atlantic Ocean'
'Brunei', 'South China Sea'
'Bulgaria', 'Black Sea'
'Burkina Faso', NULL
'Burundi', NULL
'Cambodia', 'South China Sea'
'Cameroon', 'Atlantic Ocean'
'Cameroon', 'Atlantic Ocean'
'Cameroon', 'Atlantic Ocean'
'Canada', 'Pacific Ocean'
'Canada', 'Arctic Ocean'
'Canada', 'Atlantic Ocean'
'Canada', 'Atlantic Ocean'
'Canada', 'Atlantic Ocean'
'Canada', 'Atlantic Ocean'
'Canada', 'Atlantic Ocean'
'Canada', 'Arctic Ocean'
'Canada', 'Atlantic Ocean'
'Canada', 'Atlantic Ocean'
'Canada', 'Atlantic Ocean'
'Canada', 'Pacific Ocean'
'Cape Verde', 'Atlantic Ocean'
'Cayman Islands', 'Caribbean Sea'
'Central African Republic', NULL
'Chad', NULL
'Chile', 'Pacific Ocean'
'Chile', 'Atlantic Ocean'
'China', 'East China Sea'
'China', 'Yellow Sea'
'China', 'Yellow Sea'
'China', 'Yellow Sea'
'China', 'East China Sea'
'China', 'Yellow Sea'
'China', 'South China Sea'
'China', 'South China Sea'
'China', 'South China Sea'
'China', 'East China Sea'
'Christmas Island', 'Indian Ocean'
'Cocos Islands', 'Indian Ocean'
'Colombia', 'Pacific Ocean'
'Colombia', 'Caribbean Sea'
'Colombia', 'Pacific Ocean'
'Colombia', 'Caribbean Sea'
'Colombia', 'Caribbean Sea'
'Colombia', 'Caribbean Sea'
'Colombia', 'Pacific Ocean'
'Colombia', 'Caribbean Sea'
'Colombia', 'Pacific Ocean'
'Colombia', 'Caribbean Sea'
'Colombia', 'Caribbean Sea'
'Comoros', 'Indian Ocean'
'Congo', 'Atlantic Ocean'
'Cook Islands', 'Pacific Ocean'
'Costa Rica', 'Pacific Ocean'
'Costa Rica', 'Caribbean Sea'
'Costa Rica', 'Pacific Ocean'
'Cote dIvoire', 'Atlantic Ocean'
'Croatia', 'Mediterranean Sea'
'Cuba', 'Atlantic Ocean'
'Cuba', 'Caribbean Sea'
'Cuba', 'Caribbean Sea'
'Cuba', 'Atlantic Ocean'
'Cuba', 'Gulf of Mexico'
'Cuba', 'Caribbean Sea'
'Cuba', 'Caribbean Sea'
'Cuba', 'Atlantic Ocean'
'Cuba', 'Caribbean Sea'
'Cuba', 'Atlantic Ocean'
'Cuba', 'Gulf of Mexico'
'Cuba', 'Caribbean Sea'
'Cuba', 'Atlantic Ocean'
'Cuba', 'Caribbean Sea'
'Cuba', 'Atlantic Ocean'
'Cuba', 'Caribbean Sea'
'Cuba', 'Atlantic Ocean'
'Cuba', 'Caribbean Sea'
'Cuba', 'Gulf of Mexico'
'Cuba', 'Caribbean Sea'
'Cuba', 'Caribbean Sea'
'Cuba', 'Atlantic Ocean'
'Cyprus', 'Mediterranean Sea'
'Czech Republic', NULL
'Denmark', 'Skagerrak'
'Denmark', 'North Sea'
'Denmark', 'Kattegat'
'Denmark', 'Baltic Sea'
'Djibouti', 'Red Sea'
'Djibouti', 'Gulf of Aden'
'Dominica', 'Caribbean Sea'
'Dominica', 'Atlantic Ocean'
'Dominican Republic', 'Caribbean Sea'
'Dominican Republic', 'Atlantic Ocean'
'Ecuador', 'Pacific Ocean'
'Egypt', 'Mediterranean Sea'
'Egypt', 'Red Sea'
'Egypt', 'Mediterranean Sea'
'Egypt', 'Mediterranean Sea'
'Egypt', 'Mediterranean Sea'
'Egypt', 'Mediterranean Sea'
'Egypt', 'Red Sea'
'Egypt', 'Mediterranean Sea'
'Egypt', 'Mediterranean Sea'
'Egypt', 'Mediterranean Sea'
'Egypt', 'Red Sea'
'Egypt', 'Mediterranean Sea'
'Egypt', 'Mediterranean Sea'
'El Salvador', 'Pacific Ocean'
'Equatorial Guinea', 'Atlantic Ocean'
'Eritrea', 'Red Sea'
'Estonia', 'Baltic Sea'
'Ethiopia', NULL
'Falkland Islands', 'Atlantic Ocean'
'Faroe Islands', 'Norwegian Sea'
'Faroe Islands', 'Atlantic Ocean'
'Fiji', 'Pacific Ocean'
'Finland', 'Baltic Sea'
'Finland', 'Baltic Sea'
'Finland', 'Baltic Sea'
'Finland', 'Baltic Sea'
'Finland', 'Baltic Sea'
'Finland', 'Baltic Sea'
'Finland', 'Baltic Sea'
'France', 'Mediterranean Sea'
'France', 'Atlantic Ocean'
'France', 'The Channel'
'France', 'Atlantic Ocean'
'France', 'The Channel'
'France', 'North Sea'
'France', 'Mediterranean Sea'
'France', 'The Channel'
'France', 'Mediterranean Sea'
'France', 'Atlantic Ocean'
'France', 'The Channel'
'France', 'Atlantic Ocean'
'French Guiana', 'Atlantic Ocean'
'French Polynesia', 'Pacific Ocean'
'Gabon', 'Atlantic Ocean'
'Gambia', 'Atlantic Ocean'
'Gaza Strip', 'Mediterranean Sea'
'Georgia', 'Black Sea'
'Germany', 'North Sea'
'Germany', 'Baltic Sea'
'Germany', 'North Sea'
'Germany', 'Baltic Sea'
'Germany', 'North Sea'
'Ghana', 'Atlantic Ocean'
'Gibraltar', 'Mediterranean Sea'
'Gibraltar', 'Atlantic Ocean'
'Greece', 'Mediterranean Sea'
'Greece', 'Mediterranean Sea'
'Greece', 'Mediterranean Sea'
'Greece', 'Mediterranean Sea'
'Greece', 'Mediterranean Sea'
'Greece', 'Mediterranean Sea'
'Greece', 'Mediterranean Sea'
'Greece', 'Mediterranean Sea'
'Greece', 'Mediterranean Sea'
'Greece', 'Mediterranean Sea'
'Greece', 'Mediterranean Sea'
'Greece', 'Mediterranean Sea'
'Greenland', 'Norwegian Sea'
'Greenland', 'Atlantic Ocean'
'Greenland', 'Arctic Ocean'
'Grenada', 'Caribbean Sea'
'Grenada', 'Atlantic Ocean'
'Guadeloupe', 'Caribbean Sea'
'Guadeloupe', 'Atlantic Ocean'
'Guam', 'Pacific Ocean'
'Guatemala', 'Pacific Ocean'
'Guatemala', 'Caribbean Sea'
'Guernsey', 'The Channel'
'Guinea', 'Atlantic Ocean'
'Guinea-Bissau', 'Atlantic Ocean'
'Guyana', 'Atlantic Ocean'
'Haiti', 'Caribbean Sea'
'Haiti', 'Atlantic Ocean'
'Holy See', NULL
'Honduras', 'Pacific Ocean'
'Honduras', 'Caribbean Sea'
'Honduras', 'Caribbean Sea'
'Honduras', 'Caribbean Sea'
'Honduras', 'Pacific Ocean'
'Honduras', 'Caribbean Sea'
'Hong Kong', 'South China Sea'
'Hungary', NULL
'Iceland', 'Norwegian Sea'
'Iceland', 'Atlantic Ocean'
'India', 'Gulf of Bengal'
'India', 'Indian Ocean'
'India', 'Arabian Sea'
'India', 'Gulf of Bengal'
'India', 'Arabian Sea'
'India', 'Arabian Sea'
'India', 'Indian Ocean'
'India', 'Arabian Sea'
'India', 'Arabian Sea'
'India', 'Arabian Sea'
'India', 'Arabian Sea'
'India', 'Gulf of Bengal'
'India', 'Gulf of Bengal'
'India', 'Andaman Sea'
'Indonesia', 'Sunda Sea'
'Indonesia', 'Sulawesi Sea'
'Indonesia', 'South China Sea'
'Indonesia', 'Pacific Ocean'
'Indonesia', 'Malakka Strait'
'Indonesia', 'Indian Ocean'
'Indonesia', 'Andaman Sea'
'Iran', 'Gulf of Oman'
'Iran', 'Persian Gulf'
'Iran', 'Persian Gulf'
'Iran', 'Gulf of Oman'
'Iran', 'Persian Gulf'
'Iraq', 'Persian Gulf'
'Ireland', 'Irish Sea'
'Ireland', 'Atlantic Ocean'
'Israel', 'Mediterranean Sea'
'Israel', 'Red Sea'
'Israel', 'Mediterranean Sea'
'Israel', 'Mediterranean Sea'
'Israel', 'Mediterranean Sea'
'Israel', 'Mediterranean Sea'
'Italy', 'Mediterranean Sea'
'Italy', 'Mediterranean Sea'
'Italy', 'Mediterranean Sea'
'Italy', 'Mediterranean Sea'
'Italy', 'Mediterranean Sea'
'Italy', 'Mediterranean Sea'
'Italy', 'Mediterranean Sea'
'Italy', 'Mediterranean Sea'
'Italy', 'Mediterranean Sea'
'Italy', 'Mediterranean Sea'
'Italy', 'Mediterranean Sea'
'Italy', 'Mediterranean Sea'
'Italy', 'Mediterranean Sea'
'Jamaica', 'Caribbean Sea'
'Japan', 'Sea of Japan'
'Japan', 'Sea of Japan'
'Japan', 'Pacific Ocean'
'Japan', 'Sea of Japan'
'Japan', 'Sea of Japan'
'Japan', 'Pacific Ocean'
'Japan', 'Pacific Ocean'
'Japan', 'Sea of Japan'
'Japan', 'Sea of Japan'
'Japan', 'East China Sea'
'Japan', 'Pacific Ocean'
'Japan', 'East China Sea'
'Japan', 'Sea of Japan'
'Japan', 'East China Sea'
'Japan', 'Pacific Ocean'
'Japan', 'Pacific Ocean'
'Japan', 'Pacific Ocean'
'Japan', 'Sea of Japan'
'Japan', 'East China Sea'
'Japan', 'Pacific Ocean'
'Japan', 'Pacific Ocean'
'Japan', 'Pacific Ocean'
'Japan', 'East China Sea'
'Japan', 'Pacific Ocean'
'Japan', 'Sea of Japan'
'Japan', 'Pacific Ocean'
'Japan', 'Sea of Japan'
'Japan', 'Sea of Okhotsk'
'Japan', 'Sea of Japan'
'Japan', 'Pacific Ocean'
'Japan', 'Pacific Ocean'
'Japan', 'Sea of Japan'
'Japan', 'Sea of Japan'
'Japan', 'Pacific Ocean'
'Japan', 'Sea of Japan'
'Japan', 'Pacific Ocean'
'Japan', 'Sea of Japan'
'Japan', 'Pacific Ocean'
'Jersey', 'The Channel'
'Jordan', 'Red Sea'
'Kazakstan', NULL
'Kenya', 'Indian Ocean'
'Kiribati', 'Pacific Ocean'
'Kosovo', NULL
'Kuwait', 'Persian Gulf'
'Kyrgyzstan', NULL
'Laos', NULL
'Latvia', 'Baltic Sea'
'Lebanon', 'Mediterranean Sea'
'Lesotho', NULL
'Liberia', 'Atlantic Ocean'
'Libya', 'Mediterranean Sea'
'Liechtenstein', NULL
'Lithuania', 'Baltic Sea'
'Luxembourg', NULL
'Macau', 'South China Sea'
'Macedonia', NULL
'Madagascar', 'Indian Ocean'
'Madagascar', 'Indian Ocean'
'Madagascar', 'Indian Ocean'
'Madagascar', 'Indian Ocean'
'Madagascar', 'Indian Ocean'
'Madagascar', 'Indian Ocean'
'Malawi', NULL
'Malaysia', 'South China Sea'
'Malaysia', 'Malakka Strait'
'Malaysia', 'Sulawesi Sea'
'Malaysia', 'South China Sea'
'Malaysia', 'South China Sea'
'Malaysia', 'Malakka Strait'
'Malaysia', 'Malakka Strait'
'Malaysia', 'Malakka Strait'
'Malaysia', 'South China Sea'
'Malaysia', 'Malakka Strait'
'Malaysia', 'Malakka Strait'
'Malaysia', 'South China Sea'
'Malaysia', 'Malakka Strait'
'Malaysia', 'South China Sea'
'Malaysia', 'Malakka Strait'
'Maldives', 'Pacific Ocean'
'Maldives', 'Indian Ocean'
'Mali', NULL
'Malta', 'Mediterranean Sea'
'Man', 'Irish Sea'
'Marshall Islands', 'Pacific Ocean'
'Martinique', 'Caribbean Sea'
'Martinique', 'Atlantic Ocean'
'Mauritania', 'Atlantic Ocean'
'Mauritius', 'Indian Ocean'
'Mayotte', 'Indian Ocean'
'Mexico', 'Gulf of Mexico'
'Mexico', 'Caribbean Sea'
'Mexico', 'Gulf of Mexico'
'Mexico', 'Gulf of Mexico'
'Mexico', 'Gulf of Mexico'
'Mexico', 'Pacific Ocean'
'Mexico', 'Pacific Ocean'
'Mexico', 'Caribbean Sea'
'Mexico', 'Pacific Ocean'
'Mexico', 'Pacific Ocean'
'Mexico', 'Pacific Ocean'
'Mexico', 'Pacific Ocean'
'Mexico', 'Pacific Ocean'
'Mexico', 'Pacific Ocean'
'Mexico', 'Pacific Ocean'
'Mexico', 'Gulf of Mexico'
'Mexico', 'Pacific Ocean'
'Mexico', 'Pacific Ocean'
'Micronesia', 'Pacific Ocean'
'Moldova', NULL
'Monaco', 'Mediterranean Sea'
'Mongolia', NULL
'Montenegro', 'Mediterranean Sea'
'Montserrat', 'Caribbean Sea'
'Montserrat', 'Atlantic Ocean'
'Morocco', 'Mediterranean Sea'
'Morocco', 'Atlantic Ocean'
'Mozambique', 'Indian Ocean'
'Mozambique', 'Indian Ocean'
'Mozambique', 'Indian Ocean'
'Mozambique', 'Indian Ocean'
'Mozambique', 'Indian Ocean'
'Mozambique', 'Indian Ocean'
'Mozambique', 'Indian Ocean'
'Mozambique', 'Indian Ocean'
'Myanmar', 'Andaman Sea'
'Myanmar', 'Gulf of Bengal'
'Myanmar', 'Andaman Sea'
'Myanmar', 'Andaman Sea'
'Myanmar', 'Gulf of Bengal'
'Myanmar', 'Andaman Sea'
'Namibia', 'Atlantic Ocean'
'Nauru', 'Pacific Ocean'
'Nepal', NULL
'Netherlands', 'North Sea'
'Netherlands', 'North Sea'
'Netherlands', 'North Sea'
'Netherlands', 'North Sea'
'Netherlands', 'North Sea'
'Netherlands', 'North Sea'
'Netherlands Antilles', 'Caribbean Sea'
'Netherlands Antilles', 'Atlantic Ocean'
'New Caledonia', 'Pacific Ocean'
'New Zealand', 'Pacific Ocean'
'Nicaragua', 'Pacific Ocean'
'Nicaragua', 'Caribbean Sea'
'Niger', NULL
'Nigeria', 'Atlantic Ocean'
'Niue', 'Pacific Ocean'
'Norfolk Island', 'Pacific Ocean'
'North Korea', 'Yellow Sea'
'North Korea', 'Sea of Japan'
'Northern Mariana Islands', 'Pacific Ocean'
'Norway', 'Skagerrak'
'Norway', 'Skagerrak'
'Norway', 'North Sea'
'Norway', 'Norwegian Sea'
'Norway', 'North Sea'
'Norway', 'Norwegian Sea'
'Norway', 'North Sea'
'Norway', 'Norwegian Sea'
'Norway', 'North Sea'
'Norway', 'Skagerrak'
'Norway', 'Skagerrak'
'Norway', 'Norwegian Sea'
'Norway', 'Norwegian Sea'
'Norway', 'Norwegian Sea'
'Norway', 'North Sea'
'Norway', 'Norwegian Sea'
'Norway', 'Barents Sea'
'Norway', 'Skagerrak'
'Norway', 'Skagerrak'
'Norway', 'Skagerrak'
'Oman', 'Persian Gulf'
'Oman', 'Gulf of Oman'
'Oman', 'Arabian Sea'
'Pakistan', 'Indian Ocean'
'Pakistan', 'Gulf of Oman'
'Pakistan', 'Arabian Sea'
'Palau', 'Pacific Ocean'
'Panama', 'Pacific Ocean'
'Panama', 'Pacific Ocean'
'Panama', 'Pacific Ocean'
'Panama', 'Pacific Ocean'
'Panama', 'Pacific Ocean'
'Panama', 'Caribbean Sea'
'Panama', 'Caribbean Sea'
'Panama', 'Pacific Ocean'
'Panama', 'Pacific Ocean'
'Panama', 'Caribbean Sea'
'Papua New Guinea', 'Pacific Ocean'
'Paraguay', NULL
'Peru', 'Pacific Ocean'
'Peru', 'Pacific Ocean'
'Peru', 'Pacific Ocean'
'Peru', 'Pacific Ocean'
'Peru', 'Pacific Ocean'
'Peru', 'Pacific Ocean'
'Peru', 'Pacific Ocean'
'Peru', 'Pacific Ocean'
'Peru', 'Pacific Ocean'
'Peru', 'Pacific Ocean'
'Philippines', 'Sulawesi Sea'
'Philippines', 'South China Sea'
'Philippines', 'Pacific Ocean'
'Pitcairn Islands', 'Pacific Ocean'
'Poland', 'Baltic Sea'
'Poland', 'Baltic Sea'
'Poland', 'Baltic Sea'
'Poland', 'Baltic Sea'
'Poland', 'Baltic Sea'
'Portugal', 'Atlantic Ocean'
'Portugal', 'Atlantic Ocean'
'Portugal', 'Atlantic Ocean'
'Portugal', 'Atlantic Ocean'
'Portugal', 'Atlantic Ocean'
'Portugal', 'Atlantic Ocean'
'Portugal', 'Atlantic Ocean'
'Portugal', 'Atlantic Ocean'
'Portugal', 'Atlantic Ocean'
'Portugal', 'Atlantic Ocean'
'Portugal', 'Atlantic Ocean'
'Portugal', 'Atlantic Ocean'
'Puerto Rico', 'Caribbean Sea'
'Puerto Rico', 'Atlantic Ocean'
'Qatar', 'Persian Gulf'
'Reunion', 'Indian Ocean'
'Romania', 'Black Sea'
'Romania', 'Black Sea'
'Russia', 'Sibirian Sea'
'Russia', 'Baltic Sea'
'Russia', 'Sea of Japan'
'Russia', 'Pacific Ocean'
'Russia', 'Sea of Azov'
'Russia', 'Sibirian Sea'
'Russia', 'Barents Sea'
'Russia', 'Sea of Japan'
'Russia', 'Barents Sea'
'Russia', 'Sibirian Sea'
'Russia', 'Sea of Okhotsk'
'Russia', 'Pacific Ocean'
'Russia', 'Bering Sea'
'Russia', 'Arctic Ocean'
'Russia', 'Baltic Sea'
'Russia', 'Sibirian Sea'
'Russia', 'Sea of Azov'
'Russia', 'Black Sea'
'Russia', 'Sea of Japan'
'Russia', 'Pacific Ocean'
'Russia', 'Sea of Okhotsk'
'Russia', 'Pacific Ocean'
'Russia', 'Bering Sea'
'Russia', 'Baltic Sea'
'Russia', 'Sibirian Sea'
'Russia', 'Barents Sea'
'Rwanda', NULL
'Saint Helena', 'Atlantic Ocean'
'Saint Kitts and Nevis', 'Caribbean Sea'
'Saint Kitts and Nevis', 'Atlantic Ocean'
'Saint Lucia', 'Caribbean Sea'
'Saint Lucia', 'Atlantic Ocean'
'Saint Martin', 'Caribbean Sea'
'Saint Martin', 'Atlantic Ocean'
'Saint Pierre and Miquelon', 'Atlantic Ocean'
'Saint Vincent and the Grenadines', 'Caribbean Sea'
'Saint Vincent and the Grenadines', 'Atlantic Ocean'
'Samoa', 'Pacific Ocean'
'San Marino', NULL
'Sao Tome and Principe', 'Atlantic Ocean'
'Saudi Arabia', 'Red Sea'
'Saudi Arabia', 'Persian Gulf'
'Senegal', 'Atlantic Ocean'
'Senegal', 'Atlantic Ocean'
'Senegal', 'Atlantic Ocean'
'Senegal', 'Atlantic Ocean'
'Senegal', 'Atlantic Ocean'
'Senegal', 'Atlantic Ocean'
'Serbia', NULL
'Seychelles', 'Indian Ocean'
'Sierra Leone', 'Atlantic Ocean'
'Singapore', 'South China Sea'
'Singapore', 'Malakka Strait'
'Singapore', 'Indian Ocean'
'Slovakia', NULL
'Slovenia', 'Mediterranean Sea'
'Solomon Islands', 'Pacific Ocean'
'Somalia', 'Indian Ocean'
'Somalia', 'Gulf of Aden'
'South Africa', 'Indian Ocean'
'South Africa', 'Atlantic Ocean'
'South Africa', 'Indian Ocean'
'South Africa', 'Indian Ocean'
'South Korea', 'Yellow Sea'
'South Korea', 'Sea of Japan'
'South Korea', 'East China Sea'
'Spain', 'Mediterranean Sea'
'Spain', 'Mediterranean Sea'
'Spain', 'Atlantic Ocean'
'Spain', 'Mediterranean Sea'
'Spain', 'Atlantic Ocean'
'Spain', 'Atlantic Ocean'
'Spain', 'Atlantic Ocean'
'Spain', 'Mediterranean Sea'
'Spain', 'Atlantic Ocean'
'Spain', 'Mediterranean Sea'
'Spain', 'Atlantic Ocean'
'Sri Lanka', 'Indian Ocean'
'Sri Lanka', 'Gulf of Bengal'
'Sudan', 'Red Sea'
'Suriname', 'Atlantic Ocean'
'Svalbard', 'Norwegian Sea'
'Svalbard', 'Atlantic Ocean'
'Svalbard', 'Arctic Ocean'
'Swaziland', NULL
'Sweden', 'Baltic Sea'
'Sweden', 'Baltic Sea'
'Sweden', 'Baltic Sea'
'Sweden', 'Baltic Sea'
'Sweden', 'Baltic Sea'
'Sweden', 'Baltic Sea'
'Sweden', 'Baltic Sea'
'Sweden', 'Kattegat'
'Sweden', 'Baltic Sea'
'Sweden', 'Kattegat'
'Sweden', 'Baltic Sea'
'Sweden', 'Baltic Sea'
'Sweden', 'Kattegat'
'Sweden', 'Baltic Sea'
'Sweden', 'Skagerrak'
'Sweden', 'Kattegat'
'Sweden', 'Baltic Sea'
'Sweden', 'Baltic Sea'
'Switzerland', NULL
'Syria', 'Mediterranean Sea'
'Taiwan', 'South China Sea'
'Taiwan', 'Pacific Ocean'
'Taiwan', 'East China Sea'
'Tajikistan', NULL
'Tanzania', 'Indian Ocean'
'Tanzania', 'Indian Ocean'
'Tanzania', 'Indian Ocean'
'Tanzania', 'Indian Ocean'
'Tanzania', 'Indian Ocean'
'Thailand', 'South China Sea'
'Thailand', 'Malakka Strait'
'Thailand', 'Andaman Sea'
'Timor-Leste', 'Sunda Sea'
'Timor-Leste', 'Indian Ocean'
'Togo', 'Atlantic Ocean'
'Tonga', 'Pacific Ocean'
'Trinidad and Tobago', 'Caribbean Sea'
'Trinidad and Tobago', 'Atlantic Ocean'
'Tunisia', 'Mediterranean Sea'
'Turkey', 'Black Sea'
'Turkey', 'Black Sea'
'Turkey', 'Black Sea'
'Turkey', 'Black Sea'
'Turkey', 'Black Sea'
'Turkey', 'Black Sea'
'Turkey', 'Black Sea'
'Turkey', 'Mediterranean Sea'
'Turkey', 'Black Sea'
'Turkey', 'Black Sea'
'Turkey', 'Black Sea'
'Turkey', 'Mediterranean Sea'
'Turkey', 'Black Sea'
'Turkey', 'Mediterranean Sea'
'Turkey', 'Mediterranean Sea'
'Turkey', 'Black Sea'
'Turkey', 'Mediterranean Sea'
'Turkey', 'Black Sea'
'Turkey', 'Mediterranean Sea'
'Turkey', 'Mediterranean Sea'
'Turkey', 'Black Sea'
'Turkey', 'Mediterranean Sea'
'Turkey', 'Mediterranean Sea'
'Turkmenistan', NULL
'Turks and Caicos Islands', 'Atlantic Ocean'
'Tuvalu', 'Pacific Ocean'
'Uganda', NULL
'Ukraine', 'Sea of Azov'
'Ukraine', 'Black Sea'
'Ukraine', 'Black Sea'
'Ukraine', 'Sea of Azov'
'Ukraine', 'Black Sea'
'Ukraine', 'Sea of Azov'
'Ukraine', 'Black Sea'
'Ukraine', 'Sea of Azov'
'United Arab Emirates', 'Persian Gulf'
'United Arab Emirates', 'Persian Gulf'
'United Arab Emirates', 'Persian Gulf'
'United Arab Emirates', 'Persian Gulf'
'United Arab Emirates', 'Gulf of Oman'
'United Arab Emirates', 'Persian Gulf'
'United Arab Emirates', 'Persian Gulf'
'United Kingdom', 'The Channel'
'United Kingdom', 'North Sea'
'United Kingdom', 'Irish Sea'
'United Kingdom', 'North Sea'
'United Kingdom', 'Norwegian Sea'
'United Kingdom', 'North Sea'
'United Kingdom', 'Atlantic Ocean'
'United Kingdom', 'North Sea'
'United Kingdom', 'North Sea'
'United Kingdom', 'Irish Sea'
'United Kingdom', 'Atlantic Ocean'
'United Kingdom', 'North Sea'
'United Kingdom', 'North Sea'
'United Kingdom', 'Irish Sea'
'United Kingdom', 'Irish Sea'
'United Kingdom', 'The Channel'
'United Kingdom', 'North Sea'
'United Kingdom', 'North Sea'
'United Kingdom', 'North Sea'
'United Kingdom', 'The Channel'
'United Kingdom', 'North Sea'
'United Kingdom', 'North Sea'
'United Kingdom', 'North Sea'
'United Kingdom', 'The Channel'
'United Kingdom', 'The Channel'
'United Kingdom', 'The Channel'
'United Kingdom', 'Atlantic Ocean'
'United Kingdom', 'The Channel'
'United Kingdom', 'Atlantic Ocean'
'United Kingdom', 'Irish Sea'
'United Kingdom', 'Irish Sea'
'United States', 'Pacific Ocean'
'United States', 'Atlantic Ocean'
'United States', 'Gulf of Mexico'
'United States', 'Atlantic Ocean'
'United States', 'Atlantic Ocean'
'United States', 'Pacific Ocean'
'United States', 'Atlantic Ocean'
'United States', 'Atlantic Ocean'
'United States', 'Atlantic Ocean'
'United States', 'Atlantic Ocean'
'United States', 'Gulf of Mexico'
'United States', 'Atlantic Ocean'
'United States', 'Atlantic Ocean'
'United States', 'Atlantic Ocean'
'United States', 'Gulf of Mexico'
'United States', 'Pacific Ocean'
'United States', 'Atlantic Ocean'
'United States', 'Gulf of Mexico'
'United States', 'Atlantic Ocean'
'United States', 'Atlantic Ocean'
'United States', 'Atlantic Ocean'
'United States', 'Pacific Ocean'
'United States', 'Pacific Ocean'
'United States', 'Bering Sea'
'United States', 'Arctic Ocean'
'United States', 'Gulf of Mexico'
'Uruguay', 'Atlantic Ocean'
'Uzbekistan', NULL
'Vanuatu', 'Pacific Ocean'
'Venezuela', 'Caribbean Sea'
'Venezuela', 'Caribbean Sea'
'Venezuela', 'Caribbean Sea'
'Venezuela', 'Caribbean Sea'
'Venezuela', 'Caribbean Sea'
'Venezuela', 'Caribbean Sea'
'Venezuela', 'Caribbean Sea'
'Venezuela', 'Caribbean Sea'
'Venezuela', 'Atlantic Ocean'
'Venezuela', 'Caribbean Sea'
'Venezuela', 'Caribbean Sea'
'Venezuela', 'Caribbean Sea'
'Vietnam', 'South China Sea'
'Virgin Islands', 'Caribbean Sea'
'Virgin Islands', 'Atlantic Ocean'
'Wallis and Futuna', 'Pacific Ocean'
'West Bank', NULL
'Western Sahara', 'Atlantic Ocean'
'Yemen', 'Red Sea'
'Yemen', 'Indian Ocean'
'Yemen', 'Gulf of Aden'
'Zaire', 'Atlantic Ocean'
'Zambia', NULL
'Zimbabwe', NULL

























